### ISSUE TITLE
Inconsistent num_threads default between CLI and Python API

### ISSUE THREAD

**Issue by ncclementi** [nv-morpheus/Morpheus#2212]
I was running this example https://github.com/nv-morpheus/Morpheus/blob/branch-25.06/examples/nlp_si_detection/run.sh and I convert it to run it via python. For the record, I installed morpheus via conda, and I just copy the input data in a directory called data_dir : see gist with code in  https://gist.github.com/ncclementi/c7ddc9835fa4ef306d7570788a4bdd7a

and I noticed that the python version run in 10 s while the CLI version was taking ~2min. I can confirm the output data is the same, and in both cases it's using GPU and CPP is being used.  So I did some digging and when I I checked the configs. I noticed that `num_threads` was different (see configs below), but in neither of the cases is being explicitly set.

cli config:
```yaml
Config: 
{
  "_model_max_batch_size": 32,
  "_pipeline_batch_size": 1024,
  "ae": null,
  "class_labels": [
    "address",
    "bank_acct",
    "credit_card",
    "email",
    "govt_id",
    "name",
    "password",
    "phone_num",
    "secret_keys",
    "user"
  ],
  "debug": false,
  "edge_buffer_size": 128,
  "execution_mode": "GPU",
  "feature_length": 256,
  "fil": null,
  "frozen": true,
  "log_config_file": null,
  "log_level": 10,
  "mode": "NLP",
  "num_threads": 128,
  "plugins": []
}
```

python Config:
```yaml
{'_model_max_batch_size': 32,
 '_pipeline_batch_size': 1024,
 'ae': None,
 'class_labels': ['address',
                  'bank_acct',
                  'credit_card',
                  'email',
                  'govt_id',
                  'name',
                  'password',
                  'phone_num',
                  'secret_keys',
                  'user'],
 'debug': False,
 'edge_buffer_size': 128,
 'execution_mode': <ExecutionMode.GPU: 'GPU'>,
 'feature_length': 256,
 'fil': None,
 'frozen': False,
 'log_config_file': None,
 'log_level': 30,
 'mode': <PipelineModes.NLP: 'NLP'>,
 'num_threads': 1,
 'plugins': None}
```

After looking at the source code found the bug, in the cli version the default value for num_threads is defined here: https://github.com/nv-morpheus/Morpheus/blob/761c9ea1d5afdac7a846a318d4dd0f7f82cc6b41/python/morpheus/morpheus/cli/commands.py#L264-L267
as `len(os.sched_getaffinity(0))` this on the machine I'm running is 128 .

but on the python api  this is by default 1. https://github.com/nv-morpheus/Morpheus/blob/761c9ea1d5afdac7a846a318d4dd0f7f82cc6b41/python/morpheus/morpheus/config.py#L219

I can confirm that running the cli example with `num_threads=1` runs in 10 sec. 

I don't know weather you want to make sure the defaults are consistent between CLI and Python API, in my opinion this should be the ideal scenario. Bu at least modify the documentation to make this difference explicit. 

cc: @mdemoret-nv
